### PR TITLE
Add get_pods() API method

### PR DESCRIPTION
**Pull request by alexeevit**
Hey, I just needed a method to get all my pods and didn't find it in the repo.
Here's my humble implementation.

### CODE REVIEW

**Comment by alexeevit** [comment]
BTW, I tried to add `get_pod(pod_id : str)` method, but when I added `(input: {id: "{pod_id}"})` to the query, I got GraphQL validation error. I'm not really familiar with GraphQL so would be happy if you direct me.

**Comment by justinmerrell** [comment]
Thank you for the PR! If you get a moment may you please refactor/reformat to pass the lint check: `test_ctl_commands.py:145:0: C0301: Line too long (133/100) (line-too-long)`

**Comment by alexeevit** [comment]
> Thank you for the PR! If you get a moment may you please refactor/reformat to pass the lint check: `test_ctl_commands.py:145:0: C0301: Line too long (133/100) (line-too-long)`

Easy, done.

Do you have any ideas how to build a query to get only one pod by id? I think we should add it for consistency.

**Comment by justinmerrell** [comment]
> > Thank you for the PR! If you get a moment may you please refactor/reformat to pass the lint check: `test_ctl_commands.py:145:0: C0301: Line too long (133/100) (line-too-long)`
> 
> Easy, done.
> 
> Do you have any ideas how to build a query to get only one pod by id? I think we should add it for consistency.

Assuming you already looked over this? https://graphql-spec.runpod.io/

Also super clean PR, thank you for putting in the time to make it so comprehensive and include tests :)

**Pull request merged**
